services:
  - type: web
    name: streamlit-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT"
    envVars:
      - key: PORT
        value: 8080
